# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/meizu/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter I01WD I001D,$(TARGET_DEVICE)),)

endif
